In [1]:
import pandas as pd
df = pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [2]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [3]:
df.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [6]:
import numpy as np
df.loc[0:5, 'math score'] = np.nan

df['math score'].fillna(df['math score'].median(), inplace=True)

/tmp/ipykernel_23202/533082042.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['math score'].fillna(df['math score'].median(), inplace=True)

The dataset originally has no missing values, so artificial missing values were added for demonstration. Median was used because it handles outliers better.

In [7]:
Q1 = df['math score'].quantile(0.25)
Q3 = df['math score'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[(df['math score'] >= lower) & (df['math score'] <= upper)]

Outliers were detected using the IQR method. Extreme values were removed to improve data quality.

In [8]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[['math score','reading score','writing score']] = scaler.fit_transform(
    df[['math score','reading score','writing score']]
)

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['math score','reading score','writing score']] = scaler.fit_transform(
    df[['math score','reading score','writing score']]
)

Z-score standardization was applied to center the data around zero.

In [10]:
df[['math score','reading score','writing score']].corr()

               math score  reading score  writing score
math score       1.000000       0.803662       0.785420
reading score    0.803662       1.000000       0.952531
writing score    0.785420       0.952531       1.000000

There is a strong correlation between the features,
so PCA can be useful.

In [12]:
from sklearn.decomposition import PCA

X = df[['math score','reading score','writing score']]

pca = PCA(n_components=2)
principal = pca.fit_transform(X)

print(pca.explained_variance_ratio_)

[0.89890099 0.08546703]

PCA was applied because the features are strongly correlated. The first principal component explains most of the variance.